DELETE FROM INGREDIENTE_COMPOE_POCAO;
DELETE FROM INGREDIENTE_TRATA_CONDICOES;
DELETE FROM JOGADOR_POSSUI_INGREDIENTE;
DELETE FROM JOGADOR_POSSUI_POCAO;
DELETE FROM NPC_ACOMETIDO_POR_CONDICOES;
DELETE FROM NPC_ALERGICO_A_INGREDIENTE;
DELETE FROM TRANSACAO;
DELETE FROM CONDICOES;
DELETE FROM INGREDIENTE;
DELETE FROM POCAO;
DELETE FROM NPC;
#DELETE FROM JOGADOR;

UPDATE JOGADOR SET dinheiro = 100;

INSERT INTO INGREDIENTE VALUES (1, 5, 'Cenoura', 0);
INSERT INTO INGREDIENTE VALUES (2, 2, 'Beterraba', 1);
INSERT INTO INGREDIENTE VALUES (3, 3, 'Arroz', 2);
INSERT INTO INGREDIENTE VALUES (4, 7, 'Batata Doce', 1);
INSERT INTO INGREDIENTE VALUES (5, 5, 'Sabao', 3);

INSERT INTO CONDICOES VALUES (1, 'Chatice', 'A pessoa fica muito chata, tipo muito chata mesmo', 5);

INSERT INTO NPC VALUES (1, 'Marcel Oliveira', 2, 4, 25.6, 2, 2);
INSERT INTO NPC VALUES (2, 'Nelio Cacho', 3, 5, 26.8, 3, 3);
INSERT INTO NPC VALUES (3, 'Girao', 1, 2, 21.8, 1, 1);
INSERT INTO NPC VALUES (4, 'Tonhao', 1, 2, 21.8, 1, 1);

INSERT INTO NPC_ACOMETIDO_POR_CONDICOES VALUES (1, 3);
INSERT INTO NPC_ACOMETIDO_POR_CONDICOES VALUES (1, 4);
INSERT INTO NPC_ACOMETIDO_POR_CONDICOES VALUES (1, 2);
INSERT INTO NPC_ALERGICO_A_INGREDIENTE VALUES (1, 3);
INSERT INTO INGREDIENTE_TRATA_CONDICOES VALUES (1, 1);
INSERT INTO INGREDIENTE_TRATA_CONDICOES VALUES (2, 1);