SELECT * FROM JOGADOR

SELECT * FROM POCAO

SELECT * FROM NPC

SELECT * FROM CONDICOES

SELECT * FROM INGREDIENTE

SELECT id, descricao, quantidade FROM POCAO, JOGADOR_POSSUI_POCAO
WHERE POCAO.id = JOGADOR_POSSUI_POCAO.POCAO_id
AND JOGADOR_id = 1

SELECT id, valor, nome, tempo_necessario, quantidade FROM INGREDIENTE, JOGADOR_POSSUI_INGREDIENTE
WHERE INGREDIENTE.id = JOGADOR_POSSUI_INGREDIENTE.INGREDIENTE_id
AND JOGADOR_id = 1

SELECT * FROM INGREDIENTE
LEFT JOIN JOGADOR_POSSUI_INGREDIENTE ON INGREDIENTE.id = JOGADOR_POSSUI_INGREDIENTE.INGREDIENTE_id
AND JOGADOR_id = 1

SELECT * FROM JOGADOR_POSSUI_POCAO
SELECT * FROM JOGADOR_POSSUI_INGREDIENTE

(SELECT id, valor, nome, tempo_necessario, quantidade FROM JOGADOR_POSSUI_INGREDIENTE, INGREDIENTE
WHERE JOGADOR_POSSUI_INGREDIENTE.INGREDIENTE_id = INGREDIENTE.id AND JOGADOR_id = 2)
UNION (SELECT id, valor, nome, tempo_necessario, 0 FROM INGREDIENTE WHERE id NOT IN
(SELECT id FROM JOGADOR_POSSUI_INGREDIENTE, INGREDIENTE
WHERE JOGADOR_POSSUI_INGREDIENTE.INGREDIENTE_id = INGREDIENTE.id AND JOGADOR_id = 2))

INSERT INTO INGREDIENTE VALUES (2, 2, 'Beterraba', 1)

INSERT INTO JOGADOR VALUES (5, 'Oktamolfa', 100.0)

INSERT INTO NPC VALUES (1, 'Marcel Oliveira', 2, 4, 25.6, 2, 2)
INSERT INTO NPC VALUES (2, 'Nelio Cacho', 3, 5, 26.8, 3, 3)
INSERT INTO NPC VALUES (3, 'Girao', 1, 2, 21.8, 1, 1)

INSERT INTO JOGADOR_POSSUI_POCAO VALUES (1, 1, 1)
INSERT INTO JOGADOR_POSSUI_INGREDIENTE VALUES (1, 2, 2)

DELETE FROM JOGADOR WHERE TRUE
DELETE FROM NPC WHERE TRUE